config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'homepage#index'

  resources :contact_form, only: [:create]
  get '/en', to: 'language_switch#en'
  get '/pl', to: 'language_switch#pl'

  get '/preproduction', to: 'pages#pre'
  get '/postproduction', to: 'pages#post'
  get '/work', to: 'pages#work'
  get '/onset', to: 'pages#onset'
  get '/crew', to: 'pages#crew'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  prepend_before_action do
    locale = choose_locale
    locale = :en unless locale && locale.to_sym.in?(I18n.available_locales) 
    I18n.locale = locale

    if params[:locale] && !cookies[:lang]
      cookies[:lang] = locale
    end
    cookies[:lang] = locale
  end

  helper_method :language_cache_key

  def language_cache_key
    I18n.locale
  end

  def choose_locale
    i18n_from_param = params[:locale]&.to_sym
    i18n_from_cookie = cookies[:lang]&.to_sym

    return i18n_from_param if i18n_from_param.in?(I18n.available_locales)
    return i18n_from_cookie if i18n_from_cookie.in?(I18n.available_locales)
  end
end

app/controllers/contact_form_controller.rb
class ContactFormController < ApplicationController
  def create

    UserMailer.inquiry_email(
      params[:email], 
      params[:name], 
      params[:message]
    ).deliver_now if params['g-recaptcha-response'] != ""

    redirect_to root_path, flash: { notice: t("contact_form.notice") }
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index; end
end

app/controllers/language_switch_controller.rb
class LanguageSwitchController < ApplicationController
  def en
    redirect_to root_path(locale: 'en')
  end

  def pl
    redirect_to root_path(locale: 'pl')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def pre; end
  def post; end
  def work; end
  def onset; end
  def crew; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/_contact_form.slim
h1.title.has-text-centered.has-text-primary.has-mb-60 = t("contact_form.title").upcase
.columns
  .column
    .container.has-padding-24
      = form_with url: contact_form_index_path, id: "captcha_form" do |f|
        .field
          .control.styled-input
            label.label.is-size-7-touch = t("contact_form.name").upcase
            = f.text_field :name, class: "input", placeholder: t("contact_form.name"), required: true
        .field
          .control.styled-input
            label.label.is-size-7-touch = t("contact_form.email").upcase
            = f.email_field :email, class: "input", placeholder: t("contact_form.email"), required: true
        .field
          .control.styled-input
            label.label.is-size-7-touch = t("contact_form.message").upcase
            = f.text_area :message, class: "textarea", placeholder: t("contact_form.message"), required: true
        .columns
          .column.is-flex.bottom_buttom
            .field
              .control
                = f.submit t("contact_form.send"), class: "button is-primary"
    
  .column.is-flex.is-flex-centered style="flex-direction: column" id="right_section"
    .contact
      h2.subtitle.is-size-4.is-size-5-touch.has-text-primary 
        |Phone: 
        a.is-size-5-touch href="tel:+48782085190" +48 782 085 190
      h2.subtitle.is-size-4.is-size-5-touch.has-text-primary Address: Warsaw, PL
      .social
        a.social_icon href="https://www.facebook.com/Beetroot-Studio-101839018262811/"
          span.icon.is-large = image_tag "fb", alt: "facebook logo"
        a.social_icon href="https://www.instagram.com/beetroot.studio/?hl=pl"
          span.icon.is-large = image_tag "insta", alt: "instagram logo"

app/views/homepage/index.slim
.canvas-container style="height: 100vh;"
  canvas id="canvas"
  section.main.is-flex.is-flex-centered style="z-index"
    .container.is-flex.is-flex-centered.is-flex-col id="got_image"
      = image_tag "logo-mono.png", alt: t("navbar.logo"), id: "main_logo", class: "image main_logo", 'data-tilt': true

section.contact id="contact" style="position: -webkit-sticky"
  .container
    = render 'contact_form'

/= javascript_pack_tag "parallax", 'data-turbolinks-track': 'reload'

javascript:
  const canvas = document.getElementById("canvas");
  const c = canvas.getContext("2d");

  let w;
  let h;

  const setCanvasExtents = () => {
    w = window.innerWidth;
    h = window.innerHeight;
    canvas.width = w;
    canvas.height = h;
  };

  setCanvasExtents();

  window.onresize = () => {
    setCanvasExtents();
  };

  const makeStars = count => {
    const out = [];
    for (let i = 0; i < count; i++) {
      const s = {
        x: Math.random() * 1600 - 800,
        y: Math.random() * 900 - 450,
        z: Math.random() * 1000
      };
      out.push(s);
    }
    return out;
  };

  let stars = makeStars(10000);

  const clear = () => {
    c.fillStyle = "black";
    c.fillRect(0, 0, canvas.width, canvas.height);
  };

  const putPixel = (x, y, brightness) => {
    const intensity = brightness * 255;
    const rgb = "rgb(" + intensity + "," + intensity + "," + intensity + ")";
    c.fillStyle = rgb;
    c.fillRect(x, y, 1, 1);
  };

  const moveStars = distance => {
    const count = stars.length;
    for (var i = 0; i < count; i++) {
      const s = stars[i];
      s.z -= distance;
      while (s.z <= 1) {
        s.z += 1000;
      }
    }
  };

  let prevTime;
  const init = time => {
    prevTime = time;
    requestAnimationFrame(tick);
  };

  const tick = time => {
    let elapsed = time - prevTime;
    prevTime = time;

    moveStars(elapsed * 0.1);

    clear();

    const cx = w / 2;
    const cy = h / 2;

    const count = stars.length;
    for (var i = 0; i < count; i++) {
      const star = stars[i];

      const x = cx + star.x / (star.z * 0.001);
      const y = cy + star.y / (star.z * 0.001);

      if (x < 0 || x >= w || y < 0 || y >= h) {
        continue;
      }

      const d = star.z / 1000.0;
      const b = 1 - d * d;

      putPixel(x, y, 2);
    }

    requestAnimationFrame(tick);
  };

  requestAnimationFrame(init);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beetroot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <%= yield %>
    <%= render 'partials/footer' %>
  </body>
</html>

app/views/partials/_footer.slim
footer.footer.has-padding-24
  strong Beetroot Studios © | 2020

app/views/partials/_navbar.slim
nav.navbar role="navigation" aria-label="main navigation"
  .navbar-brand
    a.navbar-item href="#{root_path}"
      = image_tag "logo-mono.png", alt: t("navbar.logo"), class: "navbar-logo"

    a.navbar-burger.burger role="button" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample"
      span aria-hidden="true"
      span aria-hidden="true"
      span aria-hidden="true"

  .navbar-menu id="navbarBasicExample"
    .navbar-end
      /a.navbar-item = t("navbar.preproduction")
      /a.navbar-item = t("navbar.onset")
      /a.navbar-item = t("navbar.postproduction")

      a.navbar-item href="#contact" = t("navbar.contact")
      a.navbar-item = t("navbar.work")
      a.navbar-item = t("navbar.about")